version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'

  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    # ports:
    #   - '2345:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'

volumes:
  data: